apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-apiserver-pvc
  namespace: helm-ns
spec:
  resources:
    requests:
      storage: 1Gi # 임시
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce # 임시. 바꿔줘야함.
  storageClassName: {scName} # 임시. 환경 스토리지클래스 확인할 것
